// <auto-generated />
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240703163648_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 1,
                            Number = 1,
                            Street = "Street 1"
                        },
                        new
                        {
                            Id = 2,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 2,
                            Number = 2,
                            Street = "Street 2"
                        },
                        new
                        {
                            Id = 3,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 3,
                            Number = 3,
                            Street = "Street 3"
                        },
                        new
                        {
                            Id = 4,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 4,
                            Number = 4,
                            Street = "Street 4"
                        },
                        new
                        {
                            Id = 5,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 5,
                            Number = 5,
                            Street = "Street 5"
                        },
                        new
                        {
                            Id = 6,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 6,
                            Number = 6,
                            Street = "Street 6"
                        },
                        new
                        {
                            Id = 7,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 7,
                            Number = 7,
                            Street = "Street 7"
                        },
                        new
                        {
                            Id = 8,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 8,
                            Number = 8,
                            Street = "Street 8"
                        },
                        new
                        {
                            Id = 9,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 9,
                            Number = 9,
                            Street = "Street 9"
                        },
                        new
                        {
                            Id = 10,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 10,
                            Number = 10,
                            Street = "Street 10"
                        },
                        new
                        {
                            Id = 11,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 11,
                            Number = 11,
                            Street = "Street 11"
                        },
                        new
                        {
                            Id = 12,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 12,
                            Number = 12,
                            Street = "Street 12"
                        },
                        new
                        {
                            Id = 13,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 13,
                            Number = 13,
                            Street = "Street 13"
                        },
                        new
                        {
                            Id = 14,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 14,
                            Number = 14,
                            Street = "Street 14"
                        },
                        new
                        {
                            Id = 15,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 15,
                            Number = 15,
                            Street = "Street 15"
                        },
                        new
                        {
                            Id = 16,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 16,
                            Number = 16,
                            Street = "Street 16"
                        },
                        new
                        {
                            Id = 17,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 17,
                            Number = 17,
                            Street = "Street 17"
                        },
                        new
                        {
                            Id = 18,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 18,
                            Number = 18,
                            Street = "Street 18"
                        },
                        new
                        {
                            Id = 19,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 19,
                            Number = 19,
                            Street = "Street 19"
                        },
                        new
                        {
                            Id = 20,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 20,
                            Number = 20,
                            Street = "Street 20"
                        },
                        new
                        {
                            Id = 21,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 21,
                            Number = 21,
                            Street = "Street 21"
                        },
                        new
                        {
                            Id = 22,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 22,
                            Number = 22,
                            Street = "Street 22"
                        },
                        new
                        {
                            Id = 23,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 23,
                            Number = 23,
                            Street = "Street 23"
                        },
                        new
                        {
                            Id = 24,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 24,
                            Number = 24,
                            Street = "Street 24"
                        },
                        new
                        {
                            Id = 25,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 25,
                            Number = 25,
                            Street = "Street 25"
                        },
                        new
                        {
                            Id = 26,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 26,
                            Number = 26,
                            Street = "Street 26"
                        },
                        new
                        {
                            Id = 27,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 27,
                            Number = 27,
                            Street = "Street 27"
                        },
                        new
                        {
                            Id = 28,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 28,
                            Number = 28,
                            Street = "Street 28"
                        },
                        new
                        {
                            Id = 29,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 29,
                            Number = 29,
                            Street = "Street 29"
                        },
                        new
                        {
                            Id = 30,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 30,
                            Number = 30,
                            Street = "Street 30"
                        },
                        new
                        {
                            Id = 31,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 31,
                            Number = 31,
                            Street = "Street 31"
                        },
                        new
                        {
                            Id = 32,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 32,
                            Number = 32,
                            Street = "Street 32"
                        },
                        new
                        {
                            Id = 33,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 33,
                            Number = 33,
                            Street = "Street 33"
                        },
                        new
                        {
                            Id = 34,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 34,
                            Number = 34,
                            Street = "Street 34"
                        },
                        new
                        {
                            Id = 35,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 35,
                            Number = 35,
                            Street = "Street 35"
                        },
                        new
                        {
                            Id = 36,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 36,
                            Number = 36,
                            Street = "Street 36"
                        },
                        new
                        {
                            Id = 37,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 37,
                            Number = 37,
                            Street = "Street 37"
                        },
                        new
                        {
                            Id = 38,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 38,
                            Number = 38,
                            Street = "Street 38"
                        },
                        new
                        {
                            Id = 39,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 39,
                            Number = 39,
                            Street = "Street 39"
                        },
                        new
                        {
                            Id = 40,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 40,
                            Number = 40,
                            Street = "Street 40"
                        },
                        new
                        {
                            Id = 41,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 41,
                            Number = 41,
                            Street = "Street 41"
                        },
                        new
                        {
                            Id = 42,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 42,
                            Number = 42,
                            Street = "Street 42"
                        },
                        new
                        {
                            Id = 43,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 43,
                            Number = 43,
                            Street = "Street 43"
                        },
                        new
                        {
                            Id = 44,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 44,
                            Number = 44,
                            Street = "Street 44"
                        },
                        new
                        {
                            Id = 45,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 45,
                            Number = 45,
                            Street = "Street 45"
                        },
                        new
                        {
                            Id = 46,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 46,
                            Number = 46,
                            Street = "Street 46"
                        },
                        new
                        {
                            Id = 47,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 47,
                            Number = 47,
                            Street = "Street 47"
                        },
                        new
                        {
                            Id = 48,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 48,
                            Number = 48,
                            Street = "Street 48"
                        },
                        new
                        {
                            Id = 49,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 49,
                            Number = 49,
                            Street = "Street 49"
                        },
                        new
                        {
                            Id = 50,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 50,
                            Number = 50,
                            Street = "Street 50"
                        },
                        new
                        {
                            Id = 51,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 51,
                            Number = 51,
                            Street = "Street 51"
                        },
                        new
                        {
                            Id = 52,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 52,
                            Number = 52,
                            Street = "Street 52"
                        },
                        new
                        {
                            Id = 53,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 53,
                            Number = 53,
                            Street = "Street 53"
                        },
                        new
                        {
                            Id = 54,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 54,
                            Number = 54,
                            Street = "Street 54"
                        },
                        new
                        {
                            Id = 55,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 55,
                            Number = 55,
                            Street = "Street 55"
                        },
                        new
                        {
                            Id = 56,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 56,
                            Number = 56,
                            Street = "Street 56"
                        },
                        new
                        {
                            Id = 57,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 57,
                            Number = 57,
                            Street = "Street 57"
                        },
                        new
                        {
                            Id = 58,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 58,
                            Number = 58,
                            Street = "Street 58"
                        },
                        new
                        {
                            Id = 59,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 59,
                            Number = 59,
                            Street = "Street 59"
                        },
                        new
                        {
                            Id = 60,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 60,
                            Number = 60,
                            Street = "Street 60"
                        },
                        new
                        {
                            Id = 61,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 61,
                            Number = 61,
                            Street = "Street 61"
                        },
                        new
                        {
                            Id = 62,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 62,
                            Number = 62,
                            Street = "Street 62"
                        },
                        new
                        {
                            Id = 63,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 63,
                            Number = 63,
                            Street = "Street 63"
                        },
                        new
                        {
                            Id = 64,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 64,
                            Number = 64,
                            Street = "Street 64"
                        },
                        new
                        {
                            Id = 65,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 65,
                            Number = 65,
                            Street = "Street 65"
                        },
                        new
                        {
                            Id = 66,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 66,
                            Number = 66,
                            Street = "Street 66"
                        },
                        new
                        {
                            Id = 67,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 67,
                            Number = 67,
                            Street = "Street 67"
                        },
                        new
                        {
                            Id = 68,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 68,
                            Number = 68,
                            Street = "Street 68"
                        },
                        new
                        {
                            Id = 69,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 69,
                            Number = 69,
                            Street = "Street 69"
                        },
                        new
                        {
                            Id = 70,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 70,
                            Number = 70,
                            Street = "Street 70"
                        },
                        new
                        {
                            Id = 71,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 71,
                            Number = 71,
                            Street = "Street 71"
                        },
                        new
                        {
                            Id = 72,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 72,
                            Number = 72,
                            Street = "Street 72"
                        },
                        new
                        {
                            Id = 73,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 73,
                            Number = 73,
                            Street = "Street 73"
                        },
                        new
                        {
                            Id = 74,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 74,
                            Number = 74,
                            Street = "Street 74"
                        },
                        new
                        {
                            Id = 75,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 75,
                            Number = 75,
                            Street = "Street 75"
                        },
                        new
                        {
                            Id = 76,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 76,
                            Number = 76,
                            Street = "Street 76"
                        },
                        new
                        {
                            Id = 77,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 77,
                            Number = 77,
                            Street = "Street 77"
                        },
                        new
                        {
                            Id = 78,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 78,
                            Number = 78,
                            Street = "Street 78"
                        },
                        new
                        {
                            Id = 79,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 79,
                            Number = 79,
                            Street = "Street 79"
                        },
                        new
                        {
                            Id = 80,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 80,
                            Number = 80,
                            Street = "Street 80"
                        },
                        new
                        {
                            Id = 81,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 81,
                            Number = 81,
                            Street = "Street 81"
                        },
                        new
                        {
                            Id = 82,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 82,
                            Number = 82,
                            Street = "Street 82"
                        },
                        new
                        {
                            Id = 83,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 83,
                            Number = 83,
                            Street = "Street 83"
                        },
                        new
                        {
                            Id = 84,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 84,
                            Number = 84,
                            Street = "Street 84"
                        },
                        new
                        {
                            Id = 85,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 85,
                            Number = 85,
                            Street = "Street 85"
                        },
                        new
                        {
                            Id = 86,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 86,
                            Number = 86,
                            Street = "Street 86"
                        },
                        new
                        {
                            Id = 87,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 87,
                            Number = 87,
                            Street = "Street 87"
                        },
                        new
                        {
                            Id = 88,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 88,
                            Number = 88,
                            Street = "Street 88"
                        },
                        new
                        {
                            Id = 89,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 89,
                            Number = 89,
                            Street = "Street 89"
                        },
                        new
                        {
                            Id = 90,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 90,
                            Number = 90,
                            Street = "Street 90"
                        },
                        new
                        {
                            Id = 91,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 91,
                            Number = 91,
                            Street = "Street 91"
                        },
                        new
                        {
                            Id = 92,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 92,
                            Number = 92,
                            Street = "Street 92"
                        },
                        new
                        {
                            Id = 93,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 93,
                            Number = 93,
                            Street = "Street 93"
                        },
                        new
                        {
                            Id = 94,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 94,
                            Number = 94,
                            Street = "Street 94"
                        },
                        new
                        {
                            Id = 95,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 95,
                            Number = 95,
                            Street = "Street 95"
                        },
                        new
                        {
                            Id = 96,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 96,
                            Number = 96,
                            Street = "Street 96"
                        },
                        new
                        {
                            Id = 97,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 97,
                            Number = 97,
                            Street = "Street 97"
                        },
                        new
                        {
                            Id = 98,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 98,
                            Number = 98,
                            Street = "Street 98"
                        },
                        new
                        {
                            Id = 99,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 99,
                            Number = 99,
                            Street = "Street 99"
                        },
                        new
                        {
                            Id = 100,
                            City = "Timisoara",
                            Country = "Romania",
                            EmployeeId = 100,
                            Number = 100,
                            Street = "Street 100"
                        });
                });

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Department1",
                            JobRole = "Software Engineer",
                            Name = "Employee1",
                            RegistrationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Department = "Department2",
                            JobRole = "Software Engineer",
                            Name = "Employee2",
                            RegistrationId = 2
                        },
                        new
                        {
                            Id = 3,
                            Department = "Department3",
                            JobRole = "Software Engineer",
                            Name = "Employee3",
                            RegistrationId = 3
                        },
                        new
                        {
                            Id = 4,
                            Department = "Department4",
                            JobRole = "Software Engineer",
                            Name = "Employee4",
                            RegistrationId = 4
                        },
                        new
                        {
                            Id = 5,
                            Department = "Department5",
                            JobRole = "Software Engineer",
                            Name = "Employee5",
                            RegistrationId = 5
                        },
                        new
                        {
                            Id = 6,
                            Department = "Department6",
                            JobRole = "Software Engineer",
                            Name = "Employee6",
                            RegistrationId = 6
                        },
                        new
                        {
                            Id = 7,
                            Department = "Department7",
                            JobRole = "Software Engineer",
                            Name = "Employee7",
                            RegistrationId = 7
                        },
                        new
                        {
                            Id = 8,
                            Department = "Department8",
                            JobRole = "Software Engineer",
                            Name = "Employee8",
                            RegistrationId = 8
                        },
                        new
                        {
                            Id = 9,
                            Department = "Department9",
                            JobRole = "Software Engineer",
                            Name = "Employee9",
                            RegistrationId = 9
                        },
                        new
                        {
                            Id = 10,
                            Department = "Department10",
                            JobRole = "Software Engineer",
                            Name = "Employee10",
                            RegistrationId = 10
                        },
                        new
                        {
                            Id = 11,
                            Department = "Department11",
                            JobRole = "Software Engineer",
                            Name = "Employee11",
                            RegistrationId = 11
                        },
                        new
                        {
                            Id = 12,
                            Department = "Department12",
                            JobRole = "Software Engineer",
                            Name = "Employee12",
                            RegistrationId = 12
                        },
                        new
                        {
                            Id = 13,
                            Department = "Department13",
                            JobRole = "Software Engineer",
                            Name = "Employee13",
                            RegistrationId = 13
                        },
                        new
                        {
                            Id = 14,
                            Department = "Department14",
                            JobRole = "Software Engineer",
                            Name = "Employee14",
                            RegistrationId = 14
                        },
                        new
                        {
                            Id = 15,
                            Department = "Department15",
                            JobRole = "Software Engineer",
                            Name = "Employee15",
                            RegistrationId = 15
                        },
                        new
                        {
                            Id = 16,
                            Department = "Department16",
                            JobRole = "Software Engineer",
                            Name = "Employee16",
                            RegistrationId = 16
                        },
                        new
                        {
                            Id = 17,
                            Department = "Department17",
                            JobRole = "Software Engineer",
                            Name = "Employee17",
                            RegistrationId = 17
                        },
                        new
                        {
                            Id = 18,
                            Department = "Department18",
                            JobRole = "Software Engineer",
                            Name = "Employee18",
                            RegistrationId = 18
                        },
                        new
                        {
                            Id = 19,
                            Department = "Department19",
                            JobRole = "Software Engineer",
                            Name = "Employee19",
                            RegistrationId = 19
                        },
                        new
                        {
                            Id = 20,
                            Department = "Department20",
                            JobRole = "Software Engineer",
                            Name = "Employee20",
                            RegistrationId = 20
                        },
                        new
                        {
                            Id = 21,
                            Department = "Department21",
                            JobRole = "Software Engineer",
                            Name = "Employee21",
                            RegistrationId = 21
                        },
                        new
                        {
                            Id = 22,
                            Department = "Department22",
                            JobRole = "Software Engineer",
                            Name = "Employee22",
                            RegistrationId = 22
                        },
                        new
                        {
                            Id = 23,
                            Department = "Department23",
                            JobRole = "Software Engineer",
                            Name = "Employee23",
                            RegistrationId = 23
                        },
                        new
                        {
                            Id = 24,
                            Department = "Department24",
                            JobRole = "Software Engineer",
                            Name = "Employee24",
                            RegistrationId = 24
                        },
                        new
                        {
                            Id = 25,
                            Department = "Department25",
                            JobRole = "Software Engineer",
                            Name = "Employee25",
                            RegistrationId = 25
                        },
                        new
                        {
                            Id = 26,
                            Department = "Department26",
                            JobRole = "Software Engineer",
                            Name = "Employee26",
                            RegistrationId = 26
                        },
                        new
                        {
                            Id = 27,
                            Department = "Department27",
                            JobRole = "Software Engineer",
                            Name = "Employee27",
                            RegistrationId = 27
                        },
                        new
                        {
                            Id = 28,
                            Department = "Department28",
                            JobRole = "Software Engineer",
                            Name = "Employee28",
                            RegistrationId = 28
                        },
                        new
                        {
                            Id = 29,
                            Department = "Department29",
                            JobRole = "Software Engineer",
                            Name = "Employee29",
                            RegistrationId = 29
                        },
                        new
                        {
                            Id = 30,
                            Department = "Department30",
                            JobRole = "Software Engineer",
                            Name = "Employee30",
                            RegistrationId = 30
                        },
                        new
                        {
                            Id = 31,
                            Department = "Department31",
                            JobRole = "Software Engineer",
                            Name = "Employee31",
                            RegistrationId = 31
                        },
                        new
                        {
                            Id = 32,
                            Department = "Department32",
                            JobRole = "Software Engineer",
                            Name = "Employee32",
                            RegistrationId = 32
                        },
                        new
                        {
                            Id = 33,
                            Department = "Department33",
                            JobRole = "Software Engineer",
                            Name = "Employee33",
                            RegistrationId = 33
                        },
                        new
                        {
                            Id = 34,
                            Department = "Department34",
                            JobRole = "Software Engineer",
                            Name = "Employee34",
                            RegistrationId = 34
                        },
                        new
                        {
                            Id = 35,
                            Department = "Department35",
                            JobRole = "Software Engineer",
                            Name = "Employee35",
                            RegistrationId = 35
                        },
                        new
                        {
                            Id = 36,
                            Department = "Department36",
                            JobRole = "Software Engineer",
                            Name = "Employee36",
                            RegistrationId = 36
                        },
                        new
                        {
                            Id = 37,
                            Department = "Department37",
                            JobRole = "Software Engineer",
                            Name = "Employee37",
                            RegistrationId = 37
                        },
                        new
                        {
                            Id = 38,
                            Department = "Department38",
                            JobRole = "Software Engineer",
                            Name = "Employee38",
                            RegistrationId = 38
                        },
                        new
                        {
                            Id = 39,
                            Department = "Department39",
                            JobRole = "Software Engineer",
                            Name = "Employee39",
                            RegistrationId = 39
                        },
                        new
                        {
                            Id = 40,
                            Department = "Department40",
                            JobRole = "Software Engineer",
                            Name = "Employee40",
                            RegistrationId = 40
                        },
                        new
                        {
                            Id = 41,
                            Department = "Department41",
                            JobRole = "Software Engineer",
                            Name = "Employee41",
                            RegistrationId = 41
                        },
                        new
                        {
                            Id = 42,
                            Department = "Department42",
                            JobRole = "Software Engineer",
                            Name = "Employee42",
                            RegistrationId = 42
                        },
                        new
                        {
                            Id = 43,
                            Department = "Department43",
                            JobRole = "Software Engineer",
                            Name = "Employee43",
                            RegistrationId = 43
                        },
                        new
                        {
                            Id = 44,
                            Department = "Department44",
                            JobRole = "Software Engineer",
                            Name = "Employee44",
                            RegistrationId = 44
                        },
                        new
                        {
                            Id = 45,
                            Department = "Department45",
                            JobRole = "Software Engineer",
                            Name = "Employee45",
                            RegistrationId = 45
                        },
                        new
                        {
                            Id = 46,
                            Department = "Department46",
                            JobRole = "Software Engineer",
                            Name = "Employee46",
                            RegistrationId = 46
                        },
                        new
                        {
                            Id = 47,
                            Department = "Department47",
                            JobRole = "Software Engineer",
                            Name = "Employee47",
                            RegistrationId = 47
                        },
                        new
                        {
                            Id = 48,
                            Department = "Department48",
                            JobRole = "Software Engineer",
                            Name = "Employee48",
                            RegistrationId = 48
                        },
                        new
                        {
                            Id = 49,
                            Department = "Department49",
                            JobRole = "Software Engineer",
                            Name = "Employee49",
                            RegistrationId = 49
                        },
                        new
                        {
                            Id = 50,
                            Department = "Department50",
                            JobRole = "Software Engineer",
                            Name = "Employee50",
                            RegistrationId = 50
                        },
                        new
                        {
                            Id = 51,
                            Department = "Department51",
                            JobRole = "Software Engineer",
                            Name = "Employee51",
                            RegistrationId = 51
                        },
                        new
                        {
                            Id = 52,
                            Department = "Department52",
                            JobRole = "Software Engineer",
                            Name = "Employee52",
                            RegistrationId = 52
                        },
                        new
                        {
                            Id = 53,
                            Department = "Department53",
                            JobRole = "Software Engineer",
                            Name = "Employee53",
                            RegistrationId = 53
                        },
                        new
                        {
                            Id = 54,
                            Department = "Department54",
                            JobRole = "Software Engineer",
                            Name = "Employee54",
                            RegistrationId = 54
                        },
                        new
                        {
                            Id = 55,
                            Department = "Department55",
                            JobRole = "Software Engineer",
                            Name = "Employee55",
                            RegistrationId = 55
                        },
                        new
                        {
                            Id = 56,
                            Department = "Department56",
                            JobRole = "Software Engineer",
                            Name = "Employee56",
                            RegistrationId = 56
                        },
                        new
                        {
                            Id = 57,
                            Department = "Department57",
                            JobRole = "Software Engineer",
                            Name = "Employee57",
                            RegistrationId = 57
                        },
                        new
                        {
                            Id = 58,
                            Department = "Department58",
                            JobRole = "Software Engineer",
                            Name = "Employee58",
                            RegistrationId = 58
                        },
                        new
                        {
                            Id = 59,
                            Department = "Department59",
                            JobRole = "Software Engineer",
                            Name = "Employee59",
                            RegistrationId = 59
                        },
                        new
                        {
                            Id = 60,
                            Department = "Department60",
                            JobRole = "Software Engineer",
                            Name = "Employee60",
                            RegistrationId = 60
                        },
                        new
                        {
                            Id = 61,
                            Department = "Department61",
                            JobRole = "Software Engineer",
                            Name = "Employee61",
                            RegistrationId = 61
                        },
                        new
                        {
                            Id = 62,
                            Department = "Department62",
                            JobRole = "Software Engineer",
                            Name = "Employee62",
                            RegistrationId = 62
                        },
                        new
                        {
                            Id = 63,
                            Department = "Department63",
                            JobRole = "Software Engineer",
                            Name = "Employee63",
                            RegistrationId = 63
                        },
                        new
                        {
                            Id = 64,
                            Department = "Department64",
                            JobRole = "Software Engineer",
                            Name = "Employee64",
                            RegistrationId = 64
                        },
                        new
                        {
                            Id = 65,
                            Department = "Department65",
                            JobRole = "Software Engineer",
                            Name = "Employee65",
                            RegistrationId = 65
                        },
                        new
                        {
                            Id = 66,
                            Department = "Department66",
                            JobRole = "Software Engineer",
                            Name = "Employee66",
                            RegistrationId = 66
                        },
                        new
                        {
                            Id = 67,
                            Department = "Department67",
                            JobRole = "Software Engineer",
                            Name = "Employee67",
                            RegistrationId = 67
                        },
                        new
                        {
                            Id = 68,
                            Department = "Department68",
                            JobRole = "Software Engineer",
                            Name = "Employee68",
                            RegistrationId = 68
                        },
                        new
                        {
                            Id = 69,
                            Department = "Department69",
                            JobRole = "Software Engineer",
                            Name = "Employee69",
                            RegistrationId = 69
                        },
                        new
                        {
                            Id = 70,
                            Department = "Department70",
                            JobRole = "Software Engineer",
                            Name = "Employee70",
                            RegistrationId = 70
                        },
                        new
                        {
                            Id = 71,
                            Department = "Department71",
                            JobRole = "Software Engineer",
                            Name = "Employee71",
                            RegistrationId = 71
                        },
                        new
                        {
                            Id = 72,
                            Department = "Department72",
                            JobRole = "Software Engineer",
                            Name = "Employee72",
                            RegistrationId = 72
                        },
                        new
                        {
                            Id = 73,
                            Department = "Department73",
                            JobRole = "Software Engineer",
                            Name = "Employee73",
                            RegistrationId = 73
                        },
                        new
                        {
                            Id = 74,
                            Department = "Department74",
                            JobRole = "Software Engineer",
                            Name = "Employee74",
                            RegistrationId = 74
                        },
                        new
                        {
                            Id = 75,
                            Department = "Department75",
                            JobRole = "Software Engineer",
                            Name = "Employee75",
                            RegistrationId = 75
                        },
                        new
                        {
                            Id = 76,
                            Department = "Department76",
                            JobRole = "Software Engineer",
                            Name = "Employee76",
                            RegistrationId = 76
                        },
                        new
                        {
                            Id = 77,
                            Department = "Department77",
                            JobRole = "Software Engineer",
                            Name = "Employee77",
                            RegistrationId = 77
                        },
                        new
                        {
                            Id = 78,
                            Department = "Department78",
                            JobRole = "Software Engineer",
                            Name = "Employee78",
                            RegistrationId = 78
                        },
                        new
                        {
                            Id = 79,
                            Department = "Department79",
                            JobRole = "Software Engineer",
                            Name = "Employee79",
                            RegistrationId = 79
                        },
                        new
                        {
                            Id = 80,
                            Department = "Department80",
                            JobRole = "Software Engineer",
                            Name = "Employee80",
                            RegistrationId = 80
                        },
                        new
                        {
                            Id = 81,
                            Department = "Department81",
                            JobRole = "Software Engineer",
                            Name = "Employee81",
                            RegistrationId = 81
                        },
                        new
                        {
                            Id = 82,
                            Department = "Department82",
                            JobRole = "Software Engineer",
                            Name = "Employee82",
                            RegistrationId = 82
                        },
                        new
                        {
                            Id = 83,
                            Department = "Department83",
                            JobRole = "Software Engineer",
                            Name = "Employee83",
                            RegistrationId = 83
                        },
                        new
                        {
                            Id = 84,
                            Department = "Department84",
                            JobRole = "Software Engineer",
                            Name = "Employee84",
                            RegistrationId = 84
                        },
                        new
                        {
                            Id = 85,
                            Department = "Department85",
                            JobRole = "Software Engineer",
                            Name = "Employee85",
                            RegistrationId = 85
                        },
                        new
                        {
                            Id = 86,
                            Department = "Department86",
                            JobRole = "Software Engineer",
                            Name = "Employee86",
                            RegistrationId = 86
                        },
                        new
                        {
                            Id = 87,
                            Department = "Department87",
                            JobRole = "Software Engineer",
                            Name = "Employee87",
                            RegistrationId = 87
                        },
                        new
                        {
                            Id = 88,
                            Department = "Department88",
                            JobRole = "Software Engineer",
                            Name = "Employee88",
                            RegistrationId = 88
                        },
                        new
                        {
                            Id = 89,
                            Department = "Department89",
                            JobRole = "Software Engineer",
                            Name = "Employee89",
                            RegistrationId = 89
                        },
                        new
                        {
                            Id = 90,
                            Department = "Department90",
                            JobRole = "Software Engineer",
                            Name = "Employee90",
                            RegistrationId = 90
                        },
                        new
                        {
                            Id = 91,
                            Department = "Department91",
                            JobRole = "Software Engineer",
                            Name = "Employee91",
                            RegistrationId = 91
                        },
                        new
                        {
                            Id = 92,
                            Department = "Department92",
                            JobRole = "Software Engineer",
                            Name = "Employee92",
                            RegistrationId = 92
                        },
                        new
                        {
                            Id = 93,
                            Department = "Department93",
                            JobRole = "Software Engineer",
                            Name = "Employee93",
                            RegistrationId = 93
                        },
                        new
                        {
                            Id = 94,
                            Department = "Department94",
                            JobRole = "Software Engineer",
                            Name = "Employee94",
                            RegistrationId = 94
                        },
                        new
                        {
                            Id = 95,
                            Department = "Department95",
                            JobRole = "Software Engineer",
                            Name = "Employee95",
                            RegistrationId = 95
                        },
                        new
                        {
                            Id = 96,
                            Department = "Department96",
                            JobRole = "Software Engineer",
                            Name = "Employee96",
                            RegistrationId = 96
                        },
                        new
                        {
                            Id = 97,
                            Department = "Department97",
                            JobRole = "Software Engineer",
                            Name = "Employee97",
                            RegistrationId = 97
                        },
                        new
                        {
                            Id = 98,
                            Department = "Department98",
                            JobRole = "Software Engineer",
                            Name = "Employee98",
                            RegistrationId = 98
                        },
                        new
                        {
                            Id = 99,
                            Department = "Department99",
                            JobRole = "Software Engineer",
                            Name = "Employee99",
                            RegistrationId = 99
                        },
                        new
                        {
                            Id = 100,
                            Department = "Department100",
                            JobRole = "Software Engineer",
                            Name = "Employee100",
                            RegistrationId = 100
                        });
                });

            modelBuilder.Entity("Domain.Address", b =>
                {
                    b.HasOne("Domain.Employee", "Employee")
                        .WithOne("Address")
                        .HasForeignKey("Domain.Address", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
